export type Scenario = {
  questionId: number;
  title: string;
  levelFit: "L3" | "L4" | "Both";
  text: string;
};

export const eotScenarioBank: Scenario[] = [
  { questionId: 3, title: "Intermittent motor/control issue", levelFit: "Both", text: "S: I had a motor or equipment circuit that would work sometimes, then stop or trip unexpectedly.\nT: I had to find the real fault instead of guessing at parts.\nA: I checked incoming voltage, control voltage, overloads, terminations, and the load side while the equipment was under demand. I worked from source to load and isolated the issue to a weak connection or control point.\nR: Once corrected, the equipment ran normally and the issue did not keep repeating." },
  { questionId: 3, title: "Breaker kept tripping", levelFit: "L3", text: "S: A circuit breaker was tripping, but the cause was not obvious.\nT: I needed to determine whether it was overload, short, ground fault, bad equipment, or a weak breaker.\nA: I separated the circuit into sections, checked the load, inspected wiring, checked for damaged insulation, and verified readings with my meter.\nR: I narrowed the issue down safely and corrected the fault instead of randomly replacing parts." },
  { questionId: 3, title: "Bad connection causing heat or dropout", levelFit: "L4", text: "S: Equipment was acting unstable and showed signs of heat, flickering, voltage drop, or inconsistent operation.\nT: I had to find the weak point before it caused bigger damage.\nA: I inspected terminations, checked connection quality, looked for discoloration, and verified voltage under load.\nR: I found the failing connection, repaired it, and prevented a larger outage or equipment failure." },
  { questionId: 4, title: "System needed to be restored fast", levelFit: "L3", text: "S: A piece of equipment needed to be brought back online quickly.\nT: I was expected to troubleshoot fast without cutting corners.\nA: I identified the energy source, used proper PPE, verified with my meter, controlled the area, and only then started troubleshooting.\nR: The equipment was restored safely, with no injury or damage." },
  { questionId: 4, title: "Coworker wanted to rush", levelFit: "L4", text: "S: A coworker or person on site wanted to hurry through a task because of time pressure.\nT: I had to keep the job moving while still protecting everyone.\nA: I explained that skipping safety steps could cause a bigger delay or injury, then followed the proper test-before-touch and isolation process.\nR: The work was completed safely and the team stayed productive." },
  { questionId: 4, title: "Troubleshooting live-adjacent equipment", levelFit: "Both", text: "S: I was working near energized equipment or in a panel environment where awareness mattered.\nT: My job was to diagnose the issue without exposing myself or others to unnecessary risk.\nA: I kept one clear work area, avoided unnecessary contact, used insulated tools and PPE, verified what was energized, and communicated what I was doing.\nR: The repair was completed safely and the equipment returned to service." },
  { questionId: 5, title: "New control system", levelFit: "L3", text: "S: I had to work on a control setup or equipment sequence I was not fully familiar with.\nT: I needed to understand it quickly enough to troubleshoot.\nA: I broke it down into power, control, safeties, load, and sequence of operation. I reviewed diagrams and verified each step with my meter.\nR: I learned the system well enough to solve the problem and became more confident with similar equipment." },
  { questionId: 5, title: "New tool or diagnostic method", levelFit: "Both", text: "S: I had to use a new meter, scanner, software, or diagnostic process.\nT: I needed to learn it while still completing the job.\nA: I focused on the core functions first, verified readings carefully, and cross-checked results against what I already knew electrically or mechanically.\nR: I was able to use the tool correctly and finish the troubleshooting." },
  { questionId: 5, title: "New equipment on site", levelFit: "Both", text: "S: I was assigned to equipment I had not worked with much before.\nT: I had to get useful fast and not slow down the team.\nA: I asked focused questions, reviewed labels, prints, and manuals, watched the sequence, and connected it back to electrical fundamentals.\nR: I became productive quickly and learned a system I could troubleshoot again later." },
  { questionId: 6, title: "Assumed the obvious part was bad", levelFit: "Both", text: "S: I once assumed the most obvious part was the problem.\nT: I had to correct the issue after realizing the first assumption was incomplete.\nA: I stopped, went back to the circuit, checked source power, controls, load, and connections in order.\nR: I found the real cause and learned to verify before replacing parts." },
  { questionId: 6, title: "Did not communicate soon enough", levelFit: "L4", text: "S: I had a task where I realized later I should have communicated a delay or issue earlier.\nT: I needed to prevent confusion and keep the team updated.\nA: I corrected it by explaining the issue clearly, giving the real status, and making sure the next steps were understood.\nR: I learned that technical work is not just fixing the problem; communication protects the schedule and the team." },
  { questionId: 6, title: "Missed a small detail", levelFit: "L3", text: "S: I missed a small detail like labeling, layout, hardware, or checking one part of the system.\nT: I had to correct it before it caused confusion or rework.\nA: I went back, fixed the detail, and added it to my personal checklist for similar jobs.\nR: The work was corrected, and I became more disciplined about final checks." },
  { questionId: 7, title: "Different troubleshooting approach", levelFit: "Both", text: "S: A coworker wanted to start replacing parts, while I wanted to test and isolate the fault first.\nT: I had to keep the job moving without creating tension.\nA: I explained that a quick meter check could save time and prevent replacing good parts.\nR: We tested first, found the issue, and completed the job more efficiently." },
  { questionId: 7, title: "Safety disagreement", levelFit: "L4", text: "S: Someone wanted to move faster than I felt was safe.\nT: I had to speak up without making it personal.\nA: I focused on the hazard, not the person. I explained the risk and suggested a safer way to finish the work.\nR: The work continued safely, and the relationship stayed professional." },
  { questionId: 7, title: "Quality disagreement", levelFit: "L4", text: "S: A coworker thought the work was good enough, but I felt it needed to be cleaner or more reliable.\nT: I needed to protect the standard without sounding difficult.\nA: I pointed to the long-term issue: future troubleshooting, inspection, safety, or reliability.\nR: We cleaned it up and finished the job to a better standard." },
  { questionId: 8, title: "Vague complaint", levelFit: "L3", text: "S: Someone reported that it just stopped working, but they had no clear details.\nT: I had to build the facts myself.\nA: I checked power, breaker status, controls, load, connections, visible damage, and recent changes.\nR: I found the issue by using a process instead of depending on perfect information." },
  { questionId: 8, title: "No prints available", levelFit: "Both", text: "S: I had to troubleshoot a circuit or system without a good diagram.\nT: I needed to figure out the path safely.\nA: I traced the circuit physically, identified source and load, labeled what I found, and verified each section with my meter.\nR: I identified the problem and left the system easier to understand for the next person." },
  { questionId: 8, title: "Equipment history unknown", levelFit: "Both", text: "S: I worked on equipment where nobody knew what had been changed before.\nT: I needed to determine whether the problem was wiring, setup, load, or component failure.\nA: I inspected for modifications, checked terminations, compared operation to normal sequence, and tested one section at a time.\nR: I isolated the fault and avoided chasing assumptions." },
  { questionId: 9, title: "Better labeling", levelFit: "L4", text: "S: A panel, circuit, or equipment area was hard to understand because labeling was unclear.\nT: I wanted to make future work safer and faster.\nA: I verified what each circuit or component controlled and improved the labeling and documentation.\nR: Future troubleshooting became easier, and the risk of mistakes went down." },
  { questionId: 9, title: "Cleaner material and tool staging", levelFit: "L3", text: "S: A job was losing time because tools and material were not staged well.\nT: I needed to make the workflow smoother.\nA: I organized material by task order, staged tools closer to the work, and kept the work area clean.\nR: The team worked faster with less confusion and fewer interruptions." },
  { questionId: 9, title: "Personal troubleshooting checklist", levelFit: "Both", text: "S: I noticed that repeated troubleshooting problems often came from skipping basic checks.\nT: I wanted a repeatable method.\nA: I created a mental checklist: source power, breaker, control voltage, safeties, load, connections, mechanical condition, then final verification.\nR: My troubleshooting became faster and more accurate." },
  { questionId: 10, title: "Equipment down", levelFit: "L3", text: "S: A piece of important equipment went down and people were waiting on it.\nT: I had to restore operation quickly.\nA: I checked the highest-impact items first: power, breaker, overload, control voltage, loose connections, and visible damage.\nR: I found the issue quickly and got the equipment running again." },
  { questionId: 10, title: "Deadline before inspection or turnover", levelFit: "Both", text: "S: A job had to be completed before an inspection, handoff, or deadline.\nT: I had to move fast without sacrificing quality.\nA: I prioritized the critical items first, communicated what was still open, and verified the work before calling it complete.\nR: The job was finished on time and avoided sloppy rework." },
  { questionId: 10, title: "Multiple issues at once", levelFit: "L4", text: "S: Several problems came up at the same time: equipment issue, material issue, and coordination with other people.\nT: I had to decide what mattered first.\nA: I prioritized safety first, then operational impact, then schedule. I handled the issue that affected the most people or equipment first.\nR: The most urgent problem was solved, and the remaining tasks stayed organized." }
];

export const eotBestExamples = {
  l3: ["Breaker kept tripping", "Vague complaint", "System needed to be restored fast", "New control system"],
  l4: ["Better labeling", "Safety disagreement", "Multiple issues at once", "Bad connection causing heat or dropout"],
  sentence: "I try to troubleshoot from facts, not assumptions. I start with safety, verify the source, isolate the system, communicate what I find, and make sure the fix prevents the same issue from coming back."
};
